### ISSUE TITLE
Non ASCII characters are not allowed in the path

### ISSUE THREAD

**Issue by asok** [ruby/uri#40]
Hi,
I'm getting such error:
```
irb(main):001:0> require 'uri'
=> false
irb(main):002:0> URI::HTTPS.build(host: 'example.com', path: '/łódź')
Traceback (most recent call last):
       10: from /Users/asokolnicki/.rubies/ruby-2.6.3/bin/irb:23:in `<main>'
        9: from /Users/asokolnicki/.rubies/ruby-2.6.3/bin/irb:23:in `load'
        8: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        7: from (irb):2
        6: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/http.rb:62:in `build'
        5: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:137:in `build'
        4: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:137:in `new'
        3: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:193:in `initialize'
        2: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:807:in `path='
        1: from /Users/asokolnicki/.rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/generic.rb:761:in `check_path'
URI::InvalidComponentError (bad component(expected absolute path component): /łódź)
```

I thought that the path component is allowed to contain any UTF-8 character.

**Comment by noraj** [comment]
cf. https://github.com/ruby/webrick/issues/110, especially this comment https://github.com/ruby/webrick/issues/110#issuecomment-1436135222.

This is because URI doesn't support RFC [3987](https://www.rfc-editor.org/rfc/rfc3987) (Internationalized
Resource Identifier (IRI)).

**Comment by jeremyevans** [comment]
No, a URI path is not allowed to contain arbitrary UTF-8 characters.  Non-ASCII UTF-8 characters must be percent encoded, and even some ASCII characters must be percent encoded.  It's true that the URI library doesn't support IRIs.  That's not a bug, there should probably be a separate library used for IRIs.

**Comment by mkasberg** [comment]
Just ran into this today... noraj's comments above seem spot-on to me.
