### ISSUE TITLE
bad URI(is not URI?): `https://x-access-token:aaa@github.com/org/repo.git/info/refs?service=git-upload-pack`

### ISSUE THREAD

**Issue by yeikel** [ruby/uri#41]
Hi there, 

Could you please clarify why this is an issue?

```
Backtrace:
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
```

**Comment by yeikel** [comment]
Closing because I was unable to reproduce it
